///inherit_svrclt_create()
TeamMap=ds_map_create()
ReadySocket=ds_list_create()
SelectedCardHolders=ds_list_create()
IsHeroSelected=false
SelectedCardHolders_Ability=ds_list_create()
IsMission=false
global.GameMoveLog=ds_list_create()
UnitsIdentifierDetails=ds_map_create()
global.AnimatorSys[0]=instance_create(0,0,obj_animator_sys)
global.SpellSys=instance_create(0,0,obj_spells_sys)
global.IsGame=false
global.SpellsIdentifier=0
global.UnitsIdentifier=0
GameWinner=-1
enum GAMESTAGE{
    PLAYERTURNS,
    STARTOFATTACKINGTURN,
    ATTACKINGTURN,
}
global.GameStage=GAMESTAGE.PLAYERTURNS
Turn=0
Turnstage[0]=0
GameLifespan=0
//camera dragging
CameraIsDrag=false
CameraXoffsetStart=0
CameraYoffsetStart=0
CameraXoffset=0
CameraYoffset=0
//units
scr_units_init()
IsDebug=false
