///scr_init_network()
enum NETWORKPKT{
    PLAYERCONNECT,
    PLAYERINIT,
    PLAYERINITCREATE,
    PLAYERDISCONNECT,
    PING,
    EXAMPLEPACKET,
    
    STARTGAME,
    TURNMOVEON,
    ATTACKINGPHASEISREADY,
    SUMMONCARD,
    CASTSPELL,
    ATTACKCARDHOLDER,
    ATTACKHERO,
    ADDCARDINTOHAND,
    REMOVECARDFROMHAND,
    ACTIVATEABILITYTARGET,
    ACTIVATEABILITY,
    ACTIVATEAFTERCARDSELECTION,
    ACTIVATEAFTERCARDSELECTIONCANCEL,
    ACTIVATEUNITCARDONME,
    HEROACTIVATEABILITYTARGET,
    HEROACTIVATEABILITY,
    PLAYERELIMINATEED,
    PLAYERWIN,
    BATTLEFIELDUPDATE,
    ROLLADIE,
    TRANSFORMCARDHOLDER,
}


//basic network variables
socketlist=ds_list_create()
socket_to_instanceid=ds_map_create()
mysocket=-1

